apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-fetcher
  template:
    metadata:
      labels:
        app: data-fetcher
    spec:
      containers:
        - name: data-fetcher
          image: jaredking13/data-fetcher:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
