apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
  labels:
    app: data-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-fetcher
  template:
    metadata:
      labels:
        app: data-fetcher
    spec:
      containers:
        - name: data-fetcher
          image: jaredking13/data-fetcher:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always

