# Use an OpenJDK image
FROM openjdk:21-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the jar file into the container
COPY /data-fetcher/build/libs/data-fetcher.jar /app/data-fetcher.jar

# Run the jar file
CMD ["java", "-jar", "data-fetcher.jar"]
